### ISSUE TITLE
NotSerializableException DStreamKafkaWriter - no way to add checkpoint to Spark stream

### ISSUE THREAD

**Issue by MarekCyzio** [cloudera/spark-kafka-writer#5]
If SparkStreamingContext.checkpoint is used in code that uses DStreamKafkaWriter, the following exception is thrown:
 ERROR OneForOneStrategy: org.cloudera.spark.streaming.kafka.DStreamKafkaWriter
java.io.NotSerializableException: org.cloudera.spark.streaming.kafka.DStreamKafkaWriter
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
...
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
        at org.apache.spark.streaming.CheckpointWriter.write(Checkpoint.scala:187)
        at org.apache.spark.streaming.scheduler.JobGenerator.doCheckpoint(JobGenerator.scala:289)
        at org.apache.spark.streaming.scheduler.JobGenerator.org$apache$spark$streaming$scheduler$JobGenerator$$processEvent(JobGenerator.scala:180)
        at org.apache.spark.streaming.scheduler.JobGenerator$$anonfun$start$1$$anon$1$$anonfun$receive$1.applyOrElse(JobGenerator.scala:86)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
        at akka.actor.ActorCell.invoke(ActorCell.scala:456)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
        at akka.dispatch.Mailbox.run(Mailbox.scala:219)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by harishreedharan** [comment]
Thanks for reporting this. I will take a look at this one early next week.

**Comment by fsalem** [comment]
Hi @harishreedharan ,

I faced the same issue when using this connector.

**Comment by adnanced** [comment]
Same problem here, did anybody solved it so far?

**Comment by fsalem** [comment]
Yeah, I've solved it. I will try to upload the code  now

**Comment by leomrocha** [comment]
Same issue here.
@fsalem can you tell when the code is updated please?
or at least a hint on how to solve it?

**Comment by fsalem** [comment]
Unfortunately, I can't commit to this project. What I did is only make each class implements Serializable interface. Kindly find attached the jar.
[spark-kafka-writer.zip](https://github.com/cloudera/spark-kafka-writer/files/164755/spark-kafka-writer.zip)

**Comment by fsalem** [comment]
Also, there is another project similar to Cloudera one but written in Java and supports only Strings till now. You can find it on the following link

https://github.com/fsalem/Spark-Kafka-Writer

**Comment by adnanced** [comment]
@fsalem thanks, Serializable actually worked. I didn't put it on all classes tho, only on `DStreamKafkaWriter` since it's instantiating `RDDKafkaWriter` inside of it. All others should be fine.

I was actually trying to solve it without including Serializable, but this will work as temp. solution.

Thanks again

**Comment by leomrocha** [comment]
@fsalem Thanx!, I'll check this out

**Comment by fsalem** [comment]
@adnanced, yeah you're right. But I just put it in all classes to be in the safe side. I think that there is another way to solve this problem by making the DStreamKafkaWriter transient which should prevent serializing it for fault tolerance. I did not tried it yet but i think it should work

**Comment by adnanced** [comment]
Actually thing with Serializable is not working with me when you try to restore checkpoint. It throws exception:
```java.io.InvalidClassException: app.spark.writer.DStreamKafkaWriter; no valid constructor```

This makes sense since it's abstract (and cannot be restored), and you need that since you have to preserve class tag. So I rewrote everything and implemented `writeToKafka` as implicit class method over the RDD and DStream from where I get the class tag. Still have some issues but it seams they are not related to this repo...

**Comment by fsalem** [comment]
@adnanced, I think that you don't need to save the state of the KafkaProducer. So, you can annotate it as Transient
